/*
 * This source file was generated by the Gradle 'init' task
 */
package com.knapsackGpu

import com.google.ortools.Loader
import com.google.ortools.algorithms.KnapsackSolver
import java.util.concurrent.Executors

fun main() {
    // Load OR-Tools library
    //System.loadLibrary("jniortools")
    Loader.loadNativeLibraries();

    val NUMBER_OF_TRIALS = 100

    // Problem setup for 10,000 problems
    val numProblems = 10000
    val maxCapacity = 50
    val numItemsPerProblem = 3

    // Randomly generate values and weights for each problem
    val random = java.util.Random(42)
    val values = Array(numProblems) { LongArray(numItemsPerProblem) { (random.nextInt(99) + 1).toLong()} }
    val weights = Array(numProblems) { LongArray(numItemsPerProblem) { (random.nextInt(49) + 1).toLong() } }
    val capacities = LongArray(numProblems) { (random.nextInt(maxCapacity) + 1).toLong() }
    var results = LongArray(numProblems)

    var totalExecutionTime = 0L

    for (k in 0 until NUMBER_OF_TRIALS) {
        // Storage for results
        results = LongArray(numProblems)

        // Measure execution time
        val startTime = System.currentTimeMillis()

        // Using a thread pool to solve problems concurrently
        val executor = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors())

        for (i in 0 until numProblems) {
            executor.execute {
                results[i] = solveKnapsack(values[i], weights[i], capacities[i])
            }
        }

        // Shutdown the executor and await termination of all tasks
        executor.shutdown()
        executor.awaitTermination(1, java.util.concurrent.TimeUnit.HOURS)

        // Print execution time
        val endTime = System.currentTimeMillis()
        //println("Threaded execution time: ${(endTime - startTime) / 1000.0} seconds")
        totalExecutionTime += endTime - startTime
    }

    println("Average Kotlin execution time: ${(totalExecutionTime/NUMBER_OF_TRIALS) / 1000.0} seconds")

    // Print the final results
    println("First 10 results:")
    for (i in 0 until 10) {
        println("Final Result for Problem ${i + 1}: Maximum value = ${results[i]}")
    }
}

// Function to solve a single knapsack problem using OR-Tools
fun solveKnapsack(values: LongArray, weights: LongArray, capacity: Long): Long {
    val solver = KnapsackSolver(KnapsackSolver.SolverType.KNAPSACK_DYNAMIC_PROGRAMMING_SOLVER, "KnapsackExample")
    solver.init(values, arrayOf(weights), longArrayOf(capacity))
    return solver.solve()
}